//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C02_BIMstaff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C02_BIMstaff()
        {
            this.C15_TimeSheet = new HashSet<C15_TimeSheet>();
            this.C18_CourseList = new HashSet<C18_CourseList>();
            this.C25_BIM_RnDproject = new HashSet<C25_BIM_RnDproject>();
            this.C27_Topic = new HashSet<C27_Topic>();
        }
    
        public int BIMstaffID { get; set; }
        public string Staff_name { get; set; }
        public string Sortname { get; set; }
        public Nullable<bool> Leader { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Deparment { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
        public string UserType { get; set; }
        public string UserStatus { get; set; }
        public Nullable<int> Descipline { get; set; }
    
        public virtual C14_Descipline C14_Descipline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C15_TimeSheet> C15_TimeSheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C18_CourseList> C18_CourseList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C25_BIM_RnDproject> C25_BIM_RnDproject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C27_Topic> C27_Topic { get; set; }
    }
}
