//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C04_DMC_PMlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C04_DMC_PMlist()
        {
            this.C01_DesignProject = new HashSet<C01_DesignProject>();
        }
    
        public int PMID { get; set; }
        public string PMName { get; set; }
        public string Sortname { get; set; }
        public Nullable<int> Descipline { get; set; }
        public Nullable<bool> Leader { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C01_DesignProject> C01_DesignProject { get; set; }
        public virtual C14_Descipline C14_Descipline { get; set; }
    }
}
