//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C06_ProjectType
    {
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectShortName { get; set; }
        public string ProjectManager { get; set; }
        public string Type { get; set; }
        public Nullable<int> Number_of_Basement { get; set; }
        public string Basement_Method_statement { get; set; }
        public Nullable<bool> Podium { get; set; }
        public Nullable<byte> SuperStructure { get; set; }
        public Nullable<int> Typical_Level { get; set; }
        public Nullable<int> Technical_room { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual C01_DesignProject C01_DesignProject { get; set; }
    }
}
