//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C11_OutsourceList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C11_OutsourceList()
        {
            this.C01_DesignProject = new HashSet<C01_DesignProject>();
        }
    
        public string OutID { get; set; }
        public string OutsourceName { get; set; }
        public string Location { get; set; }
        public string OutsLocation { get; set; }
        public string OutsDescipline { get; set; }
        public Nullable<bool> WorkOnSite { get; set; }
        public Nullable<bool> Outsourcing { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C01_DesignProject> C01_DesignProject { get; set; }
    }
}
