//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C16_WorkType
    {
        public int WorkID { get; set; }
        public string WorkName { get; set; }
        public Nullable<int> WorkGroup { get; set; }
    
        public virtual C16a_WorkTypeGroup C16a_WorkTypeGroup { get; set; }
    }
}
