//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C18_CourseList
    {
        public int IDKhoahoc { get; set; }
        public int MemberID { get; set; }
        public string TenKhoahoc { get; set; }
        public string MemberName { get; set; }
        public string NamDaotao { get; set; }
        public string Bomondaotao { get; set; }
        public Nullable<double> SoKhoahoc { get; set; }
        public Nullable<System.DateTime> Ngaybatdau { get; set; }
        public Nullable<System.DateTime> NgayKetthuc { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual C02_BIMstaff C02_BIMstaff { get; set; }
        public virtual C21_SubjectList C21_SubjectList { get; set; }
    }
}
