//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C20_StudentList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C20_StudentList()
        {
            this.C18_CourseList_Detail = new HashSet<C18_CourseList_Detail>();
        }
    
        public int MaHV { get; set; }
        public string HoLot { get; set; }
        public string Congty { get; set; }
        public string Chucvu { get; set; }
        public string ChuyenMon { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string ĐiemChuyenCan { get; set; }
        public string ĐiemTongKet { get; set; }
        public string KetquaXepLoai { get; set; }
        public string KhoaHoc { get; set; }
        public Nullable<int> Sub_Contractor { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C18_CourseList_Detail> C18_CourseList_Detail { get; set; }
        public virtual C19_SubContractList C19_SubContractList { get; set; }
    }
}
