//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C24_IssueList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C24_IssueList()
        {
            this.C33_SolutionOffer = new HashSet<C33_SolutionOffer>();
        }
    
        public int ID { get; set; }
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public int MemberID { get; set; }
        public string IssueCode { get; set; }
        public string IssueStatus { get; set; }
        public Nullable<int> NoOfRepeat { get; set; }
        public string Sources { get; set; }
        public string Level { get; set; }
        public string Tower { get; set; }
        public string Grid { get; set; }
        public string IssueDescription { get; set; }
        public string ConstructorSolution { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public Nullable<int> Revision { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string SendTo { get; set; }
        public string Cc_to { get; set; }
        public string From { get; set; }
        public string Descipline { get; set; }
        public string Matrix1 { get; set; }
        public string Matrix2 { get; set; }
        public string Priority { get; set; }
    
        public virtual C01_DesignProject C01_DesignProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C33_SolutionOffer> C33_SolutionOffer { get; set; }
    }
}
