//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C27_Topic
    {
        public int ID { get; set; }
        public int MemberID { get; set; }
        public string TopicName { get; set; }
        public string TopicType { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> PrenstationDate { get; set; }
        public string Content { get; set; }
        public string Status { get; set; }
        public string AttachFileResult { get; set; }
        public string Link { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual C02_BIMstaff C02_BIMstaff { get; set; }
    }
}
