//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C30_NTP_ProjectDetails
    {
        public int ID { get; set; }
        public string ProjectID { get; set; }
        public int NTPID { get; set; }
        public string MemberTakecare { get; set; }
    
        public virtual C01_DesignProject C01_DesignProject { get; set; }
        public virtual C28_NTP C28_NTP { get; set; }
    }
}
