//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C32_ProjectPhase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C32_ProjectPhase()
        {
            this.C31_ProjectPhaseDetails = new HashSet<C31_ProjectPhaseDetails>();
        }
    
        public int PhaseID { get; set; }
        public string PhaseName { get; set; }
        public string Desription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C31_ProjectPhaseDetails> C31_ProjectPhaseDetails { get; set; }
    }
}
