//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BIMReports.com.cbimtech.TimesheetServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TimesheetServiceSoap", Namespace="http://services.cbimtech.com/WebServices/")]
    public partial class TimesheetService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DanhsachTimesheetTheoProjectIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback DanhsachTimesheetTheoMemberIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback WorkNameListOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindWorkNameByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindWorkInGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddWorkDoneOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TimesheetService() {
            this.Url = global::BIMReports.Properties.Settings.Default.BIMReports_com_cbimtech_TimesheetServices_TimesheetService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DanhsachTimesheetTheoProjectIDCompletedEventHandler DanhsachTimesheetTheoProjectIDCompleted;
        
        /// <remarks/>
        public event DanhsachTimesheetTheoMemberIDCompletedEventHandler DanhsachTimesheetTheoMemberIDCompleted;
        
        /// <remarks/>
        public event WorkNameListCompletedEventHandler WorkNameListCompleted;
        
        /// <remarks/>
        public event FindWorkNameByIDCompletedEventHandler FindWorkNameByIDCompleted;
        
        /// <remarks/>
        public event FindWorkInGroupCompletedEventHandler FindWorkInGroupCompleted;
        
        /// <remarks/>
        public event AddWorkDoneCompletedEventHandler AddWorkDoneCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/DanhsachTimesheetTheoProjectID", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimesheetOutput[] DanhsachTimesheetTheoProjectID(string id) {
            object[] results = this.Invoke("DanhsachTimesheetTheoProjectID", new object[] {
                        id});
            return ((TimesheetOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void DanhsachTimesheetTheoProjectIDAsync(string id) {
            this.DanhsachTimesheetTheoProjectIDAsync(id, null);
        }
        
        /// <remarks/>
        public void DanhsachTimesheetTheoProjectIDAsync(string id, object userState) {
            if ((this.DanhsachTimesheetTheoProjectIDOperationCompleted == null)) {
                this.DanhsachTimesheetTheoProjectIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDanhsachTimesheetTheoProjectIDOperationCompleted);
            }
            this.InvokeAsync("DanhsachTimesheetTheoProjectID", new object[] {
                        id}, this.DanhsachTimesheetTheoProjectIDOperationCompleted, userState);
        }
        
        private void OnDanhsachTimesheetTheoProjectIDOperationCompleted(object arg) {
            if ((this.DanhsachTimesheetTheoProjectIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DanhsachTimesheetTheoProjectIDCompleted(this, new DanhsachTimesheetTheoProjectIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/DanhsachTimesheetTheoMemberID", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TimesheetOutput[] DanhsachTimesheetTheoMemberID(string memberid) {
            object[] results = this.Invoke("DanhsachTimesheetTheoMemberID", new object[] {
                        memberid});
            return ((TimesheetOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void DanhsachTimesheetTheoMemberIDAsync(string memberid) {
            this.DanhsachTimesheetTheoMemberIDAsync(memberid, null);
        }
        
        /// <remarks/>
        public void DanhsachTimesheetTheoMemberIDAsync(string memberid, object userState) {
            if ((this.DanhsachTimesheetTheoMemberIDOperationCompleted == null)) {
                this.DanhsachTimesheetTheoMemberIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDanhsachTimesheetTheoMemberIDOperationCompleted);
            }
            this.InvokeAsync("DanhsachTimesheetTheoMemberID", new object[] {
                        memberid}, this.DanhsachTimesheetTheoMemberIDOperationCompleted, userState);
        }
        
        private void OnDanhsachTimesheetTheoMemberIDOperationCompleted(object arg) {
            if ((this.DanhsachTimesheetTheoMemberIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DanhsachTimesheetTheoMemberIDCompleted(this, new DanhsachTimesheetTheoMemberIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/WorkNameList", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WorkNameOutput[] WorkNameList() {
            object[] results = this.Invoke("WorkNameList", new object[0]);
            return ((WorkNameOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void WorkNameListAsync() {
            this.WorkNameListAsync(null);
        }
        
        /// <remarks/>
        public void WorkNameListAsync(object userState) {
            if ((this.WorkNameListOperationCompleted == null)) {
                this.WorkNameListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWorkNameListOperationCompleted);
            }
            this.InvokeAsync("WorkNameList", new object[0], this.WorkNameListOperationCompleted, userState);
        }
        
        private void OnWorkNameListOperationCompleted(object arg) {
            if ((this.WorkNameListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WorkNameListCompleted(this, new WorkNameListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/FindWorkNameByID", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WorkNameOutput FindWorkNameByID(int id) {
            object[] results = this.Invoke("FindWorkNameByID", new object[] {
                        id});
            return ((WorkNameOutput)(results[0]));
        }
        
        /// <remarks/>
        public void FindWorkNameByIDAsync(int id) {
            this.FindWorkNameByIDAsync(id, null);
        }
        
        /// <remarks/>
        public void FindWorkNameByIDAsync(int id, object userState) {
            if ((this.FindWorkNameByIDOperationCompleted == null)) {
                this.FindWorkNameByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindWorkNameByIDOperationCompleted);
            }
            this.InvokeAsync("FindWorkNameByID", new object[] {
                        id}, this.FindWorkNameByIDOperationCompleted, userState);
        }
        
        private void OnFindWorkNameByIDOperationCompleted(object arg) {
            if ((this.FindWorkNameByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindWorkNameByIDCompleted(this, new FindWorkNameByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/FindWorkInGroup", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WorkNameOutput[] FindWorkInGroup(int groupID) {
            object[] results = this.Invoke("FindWorkInGroup", new object[] {
                        groupID});
            return ((WorkNameOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void FindWorkInGroupAsync(int groupID) {
            this.FindWorkInGroupAsync(groupID, null);
        }
        
        /// <remarks/>
        public void FindWorkInGroupAsync(int groupID, object userState) {
            if ((this.FindWorkInGroupOperationCompleted == null)) {
                this.FindWorkInGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindWorkInGroupOperationCompleted);
            }
            this.InvokeAsync("FindWorkInGroup", new object[] {
                        groupID}, this.FindWorkInGroupOperationCompleted, userState);
        }
        
        private void OnFindWorkInGroupOperationCompleted(object arg) {
            if ((this.FindWorkInGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindWorkInGroupCompleted(this, new FindWorkInGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.cbimtech.com/WebServices/AddWorkDone", RequestNamespace="http://services.cbimtech.com/WebServices/", ResponseNamespace="http://services.cbimtech.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddWorkDone(TimesheetInput enity) {
            object[] results = this.Invoke("AddWorkDone", new object[] {
                        enity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddWorkDoneAsync(TimesheetInput enity) {
            this.AddWorkDoneAsync(enity, null);
        }
        
        /// <remarks/>
        public void AddWorkDoneAsync(TimesheetInput enity, object userState) {
            if ((this.AddWorkDoneOperationCompleted == null)) {
                this.AddWorkDoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddWorkDoneOperationCompleted);
            }
            this.InvokeAsync("AddWorkDone", new object[] {
                        enity}, this.AddWorkDoneOperationCompleted, userState);
        }
        
        private void OnAddWorkDoneOperationCompleted(object arg) {
            if ((this.AddWorkDoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddWorkDoneCompleted(this, new AddWorkDoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.cbimtech.com/WebServices/")]
    public partial class TimesheetOutput {
        
        private int memberIDField;
        
        private string memberNameField;
        
        private string projectIDField;
        
        private System.DateTime recordDateField;
        
        private string projectNameField;
        
        private string workTypeField;
        
        private int workGroupField;
        
        private double hourField;
        
        private double otField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int MemberID {
            get {
                return this.memberIDField;
            }
            set {
                this.memberIDField = value;
            }
        }
        
        /// <remarks/>
        public string MemberName {
            get {
                return this.memberNameField;
            }
            set {
                this.memberNameField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectID {
            get {
                return this.projectIDField;
            }
            set {
                this.projectIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RecordDate {
            get {
                return this.recordDateField;
            }
            set {
                this.recordDateField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
            }
        }
        
        /// <remarks/>
        public string WorkType {
            get {
                return this.workTypeField;
            }
            set {
                this.workTypeField = value;
            }
        }
        
        /// <remarks/>
        public int WorkGroup {
            get {
                return this.workGroupField;
            }
            set {
                this.workGroupField = value;
            }
        }
        
        /// <remarks/>
        public double Hour {
            get {
                return this.hourField;
            }
            set {
                this.hourField = value;
            }
        }
        
        /// <remarks/>
        public double OT {
            get {
                return this.otField;
            }
            set {
                this.otField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.cbimtech.com/WebServices/")]
    public partial class TimesheetInput {
        
        private int memberIDField;
        
        private string projectIDField;
        
        private System.DateTime recordDateField;
        
        private int workIDField;
        
        private int hourField;
        
        private int otField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int MemberID {
            get {
                return this.memberIDField;
            }
            set {
                this.memberIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectID {
            get {
                return this.projectIDField;
            }
            set {
                this.projectIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RecordDate {
            get {
                return this.recordDateField;
            }
            set {
                this.recordDateField = value;
            }
        }
        
        /// <remarks/>
        public int WorkID {
            get {
                return this.workIDField;
            }
            set {
                this.workIDField = value;
            }
        }
        
        /// <remarks/>
        public int Hour {
            get {
                return this.hourField;
            }
            set {
                this.hourField = value;
            }
        }
        
        /// <remarks/>
        public int OT {
            get {
                return this.otField;
            }
            set {
                this.otField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.cbimtech.com/WebServices/")]
    public partial class WorkNameOutput {
        
        private int workIDField;
        
        private string workNameField;
        
        private System.Nullable<int> workGroupField;
        
        /// <remarks/>
        public int WorkID {
            get {
                return this.workIDField;
            }
            set {
                this.workIDField = value;
            }
        }
        
        /// <remarks/>
        public string WorkName {
            get {
                return this.workNameField;
            }
            set {
                this.workNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> WorkGroup {
            get {
                return this.workGroupField;
            }
            set {
                this.workGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DanhsachTimesheetTheoProjectIDCompletedEventHandler(object sender, DanhsachTimesheetTheoProjectIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DanhsachTimesheetTheoProjectIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DanhsachTimesheetTheoProjectIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimesheetOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimesheetOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DanhsachTimesheetTheoMemberIDCompletedEventHandler(object sender, DanhsachTimesheetTheoMemberIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DanhsachTimesheetTheoMemberIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DanhsachTimesheetTheoMemberIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimesheetOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimesheetOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WorkNameListCompletedEventHandler(object sender, WorkNameListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WorkNameListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WorkNameListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WorkNameOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WorkNameOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FindWorkNameByIDCompletedEventHandler(object sender, FindWorkNameByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindWorkNameByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindWorkNameByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WorkNameOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WorkNameOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FindWorkInGroupCompletedEventHandler(object sender, FindWorkInGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindWorkInGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindWorkInGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WorkNameOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WorkNameOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AddWorkDoneCompletedEventHandler(object sender, AddWorkDoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddWorkDoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddWorkDoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591